name: Docker

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io


jobs:
  build:
    strategy:
      matrix:
        include:
          - sdk: '4.8'
            sdkFull: '4.8.2502'
            image: windowsservercore-ltsc2022
            runner: windows-2022
            build: true

    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        if: matrix.build == true
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: matrix.build == true
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image ${{ matrix.sdk }}-${{ matrix.image }}
        if: matrix.build == true
        run: |
          docker build ${{ github.workspace }}/src/sdk/${{ matrix.sdk }}/${{ matrix.image }} --tag ghcr.io/smkanadl/framework-sdk:${{ matrix.sdk }}-${{ matrix.image }} --tag ghcr.io/smkanadl/framework-sdk:${{ matrix.sdkFull }}-${{ matrix.image }}
          docker push ghcr.io/smkanadl/framework-sdk:${{ matrix.sdk }}-${{ matrix.image }}
          docker push ghcr.io/smkanadl/framework-sdk:${{ matrix.sdkFull }}-${{ matrix.image }}
